name: ci-image

on:
  push:                # 只要 push 就跑
    branches: [main]
  pull_request:        # 開 PR 也跑（只 build）

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:

    # 1. 取出程式碼
    - uses: actions/checkout@v4

    # 2. 建立 buildx 環境（支援多平台）
    - uses: docker/setup-buildx-action@v3

    # 3. 登入 Docker Hub（用 Secrets）
    - uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 4. 自動產生 tag（latest + sha-xxxxxxx）
    - id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ secrets.DOCKER_USERNAME }}/2025cloud
        tags: |
          type=raw,value=latest,enable={{is_default_branch}}
          type=sha,format=short

    # 5. build & push
    - uses: docker/build-push-action@v5
      with:
        push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
